#!/bin/bash

# dotfiles 直下に移動する 
cd `dirname $0`; cd ../../

# ライブラリスクリプトを読み込む
source etc/lib/exist_dir.sh

# 環境に ~/.fzf ディレクトリが存在しなければ終了
exist_dir ~/.fzf || exit 1

# ~/.zshrc に設定が存在すれば終了
grep -q "source ~/.fzf.zsh" ~/.zshrc
[ `echo $?` -eq 0 ] && exit 2

# 環境に fzf はインストールされているが ~/.zshrc に設定が欠けているので追記
echo "" >> ~/.zshrc  ## 空行を挿入するための `echo`
cat << EOS >> ~/.zshrc
#
# etc/deploy/040_deploy_fzf
#
source ~/.fzf.zsh
EOS
