#!/bin/bash

# dotfiles 直下に移動する 
cd `dirname $0`; cd ../../

# ライブラリスクリプトを読み込む
source etc/lib/exist_dir.sh
source etc/env/path

# 環境に ~/.vim/dein ディレクトリが存在しなければ終了
exist_dir $DEIN_PATH || exit 1

# ~/.vim/dein に dein.toml をコピー
cp etc/deploy/dein/dein.toml $DEIN_PATH/

exit 0
