#!/bin/bash

# dotfiles 直下に移動する 
cd `dirname $0`; cd ../../

# ライブラリスクリプトを読み込む
source etc/env/path

# ~/.vimrc に設定が存在すれば終了
grep -q "vim-airline/vim-airline" $VIMRC
[ `echo $?` -eq 0 ] && exit 2

# ~/.vimrc に vim-airline の設定が欠けているので追記
cat << EOS >> $VIMRC

" vim-airline/vim-airline
set laststatus=2
set t_Co=256
let g:airline_powerline_fonts=1
let g:airline_left_sep = '▶'
let g:airline_right_sep = '◀'
EOS
