#!/bin/bash

# dotfiles 直下に移動する 
cd `dirname $0`; cd ../../

# ライブラリスクリプトを読み込む
source etc/env/path

# ~/.vimrc に設定が存在すれば終了
grep -q "majutsushi/tagbar" $VIMRC
[ `echo $?` -eq 0 ] && exit 2

# ~/.vimrc に majutsushi/tagbar の設定が欠けているので追記
cat << EOS >> $VIMRC

" majutsushi/tagbar
nmap <F3> :TagbarToggle<CR>
EOS
