#!/bin/bash

# dotfiles 直下に移動する 
cd `dirname $0`; cd ../../

# ライブラリスクリプトを読み込む
source etc/lib/exist_dir.sh
source etc/env/path

# FZF がシステムにインストールされていなければ終了する
exist_dir $FZF_PATH || exit 1

# ~/.vimrc に設定が存在すれば終了する
grep -q "junegunn/fzf" $VIMRC
[ `echo $?` -eq 0 ] && exit 2

# ~/.vimrc に FZF の設定が欠けているので追記
cat << EOS >> $VIMRC

" junegunn/fzf
set rtp+=~/.fzf
EOS
