#!/bin/bash -eu

function usage() {
  cat <<EOF 1>&2
Description:
  $(basename ${0}) は dein.vim を使って Vim で flake8 による文法チェックを行うプラグインをインストールするスクリプトである。
  $(basename ${0}) によりインストールされる Vim プラグインは以下の通り。

  [[plugins]]
  repo = 'scrooloose/syntastic'

  $(basename ${0}) は以下の条件を満たす場合のみ実行する。
    1. システムに Python がインストールされていること
    2. システムに Vim がインストールされていること
    3. ~/.vimrc にプラグインの設定がされていないこと

Usage:
  $(basename ${0})

Options:
  -h        print this
  -x        dry run
EOF
  exit 1
}

# dotfiles 直下に移動する 
cd `dirname $0`; cd ../../

# ライブラリスクリプトを読み込む
. etc/env/path
. etc/lib/dry_run.sh
. etc/lib/installed_command.sh

while getopts hx OPT
do
  case "$OPT" in
    h) usage
	   ;;
    x) enable_dryrun
       ;;
    \?) usage
        ;;
  esac
done

# システムに `python` がインストールされていない場合は終了する
[[ `installed_command python` -eq 0 ]] || exit 2

# システムに `vim` がインストールされていない場合は終了する
[[ `installed_command vim` -eq 0 ]] || exit 3

# ~/.vimrc に設定が存在すれば終了する
grep -q "syntastic_python_checkers" $VIMRC
[ `echo $?` -eq 0 ] && exit 4

echo "test"
exit 0

# ~/.vimrc に Shougo/neocomplete.vim の設定が欠けているので追記
cat << EOS >> $VIMRC

" Shougo/neocomplete.vim
" Disable AutoComplPop
let g:acp_enableAtStartUp = 0
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_ignore_case = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#enable_underbar_completion = 1
let g:neocomplete#enable_camel_case_completion = 1
let g:neocomplete#auto_completion_start_length = 2
" Set minimum syntax keyword length
let g:neocomplete#sources#syntax#min_keyword_length = 2
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'
EOS
