#!/bin/bash

# dotfiles 直下に移動する 
cd `dirname $0`; cd ../../

# ライブラリスクリプトを読み込む
source etc/lib/exist_dir.sh

# 環境に /bin/zsh がディレクトリが存在すれば終了
exist_dir /bin/zsh && exit 1

# `yum` を使ってインストールする
sudo yum -y install zsh

# シェルを zsh に変更する
chsh
