#!/bin/bash

# dotfiles 直下に移動する 
cd `dirname $0`; cd ../../

# ライブラリスクリプトを読み込む
source etc/lib/installed_command.sh

# 環境に fzf がインストールされていれば終了
installed_command fzf && exit 1

# Github からプロジェクトを `clone` する
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf

# インストールスクリプトを実行する
sh ~/.fzf/install

