#!/bin/bash

# dotfiles 直下に移動する 
cd `dirname $0`; cd ../../

# ライブラリスクリプトを読み込む
source etc/lib/installed_by_yum.sh

# 環境に `yum` を使って `tree` がインストールされていなければインストールする
installed_by_yum tree || sudo yum -y install tree 
