#!/bin/bash -eu

# dotfiles 直下に移動する 
cd `dirname $0`; cd ../../

# ライブラリスクリプトを読み込む
source etc/lib/installed_command.sh

# 環境に `hg` がインストールされていれば終了
installed_command hg && exit 1 

# `wget` を使って Mercurial の RPM をダウンロードする
# RPM はテンポラリディレクトリにダウンロードし、インストール後に削除する
temp_dir=~/.hg_install
mercurial_rpm_url=https://www.mercurial-scm.org/release/centos6/RPMS/x86_64/mercurial-3.9.2-1.x86_64.rpm

mkdir "$temp_dir"
wget "$mercurial_rpm_url" -P "$temp_dir"

mercurial_rpm=mercurial-3.9.2-1.x86_64.rpm  # ここは正規表現で切り出したい
sudo rpm -ivh "$temp_dir/$mercurial_rpm"

rm -fr "$temp_dir"
exit 0
