#!/bin/bash -eu
#
# @(#) 081_mercurial_hst ver.1.0.0 2016/12/30
#
# Usage:
#   081_mercurial_hst
#
# Description:
#   Mercurial の `hg` コマンドを補助する以下のスクリプトのシンボリックリンクを作成する。
#     - etc/install/mercurial/hst.sh
#   シンボリックリンクは ~/bin/ に作成する。
#   シンボリックリンク作成条件は以下の通り。
#     - システムに Mercurial がインストールされていること
#     - システムに FZF がインストールされていること
#
###########################################################################

# dotfiles 直下に移動する 
cd `dirname $0`; cd ../../

# ライブラリスクリプトを読み込む
source etc/lib/installed_command.sh
source etc/lib/create_dir.sh

# 環境に `hg` がインストールされていれば終了
installed_command hg || exit 1
# 環境に `FZF` がインストールされていれば終了
installed_command fzf || exit 2

# ~/bin ディレクトリが存在しなければ作成する
create_dir "~/bin"

# ~/bin に hsh.sh のシンボリックリンクを作成する
ln -sf `pwd`/etc/install/mercurial/hst.sh ~/bin/hst
exit 0
